version: "3"
  
services:
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd3
    restart: always
    environment:
      - ETCDCTL_API=3
    command:
      - etcd
      - --name=etcd3
      - --data-dir=/etcd-data
      - --listen-client-urls=https://192.168.3.103:2379
      - --advertise-client-urls=https://192.168.3.103:2379
      - --listen-peer-urls=https://192.168.3.103:2380
      - --initial-advertise-peer-urls=https://192.168.3.103:2380
      - --initial-cluster=etcd1=https://192.168.3.101:2380,etcd2=https://192.168.3.102:2380,etcd3=https://192.168.3.103:2380
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster-state=new
      # client端证书
      - --client-cert-auth
      - --trusted-ca-file=/etcd-certs/ca.pem
      - --cert-file=/etcd-certs/192.168.3.103.pem
      - --key-file=/etcd-certs/192.168.3.103-key.pem
      # peer端证书
      - --peer-client-cert-auth
      - --peer-trusted-ca-file=/etcd-certs/ca.pem
      - --peer-cert-file=/etcd-certs/peer-192.168.3.103.pem
      - --peer-key-file=/etcd-certs/peer-192.168.3.103-key.pem
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - $PWD/etcd-data:/etcd-data
      - $PWD/certs:/etcd-certs
    network_mode: "host"

