version: '3'

services:
  mysql-8.0:
    image: mysql:8.0
    container_name: mysql-8.0
    restart: always
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
  
