version: '3'
services:
  sentinel1:
    image: redis:6.2.6
    container_name: redis-sentinel-1
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - $PWD/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - 26381:26379

  sentinel2:
    image: redis:6.2.6
    container_name: redis-sentinel-2
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - $PWD/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    ports:
    - 26382:26379

  sentinel3:
    image: redis:6.2.6
    container_name: redis-sentinel-3
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - $PWD/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - 26383:26379

networks:
  default:
    external:
      name: redis-net
      #name: redis_default
