version: '3'

services:
  mysql8.0-ssl:
    image: mysql:8.0.18
    container_name: mysql8.0-ssl
    restart: always
    ports:
      - 3306:3306
      # 33062专门为管理连接配置 TCP/IP 端口，作为3306端口出现too many connection时使用
      - 33062:33062
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - $PWD/my.cnf:/etc/mysql/my.cnf
      - $PWD/mysql-data:/var/lib/mysql
