version: '3.1'
services:
  mongo:
    image: mongo:4.1.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
    - 27017:27017
    volumes:
    - $PWD/data:/etc/mongo
