version: '3.1'

services:

    redis-exporter:
        image: bitnami/redis-exporter:1.27.1
        ports:
            - 9121:9121
        command:
            - "-redis.addr=redis://192.168.111.128:6379"
            - "-redis.password=123456"
        restart: always

#    redis-exporter2:
#        image: bitnami/redis-exporter:1.27.1
#        ports:
#            - 9122:9121
#        command:
#            - "-redis.addr=redis://192.168.7.92:6379"
#            - "-redis.password=U2FsdGVkX1@28Lik"
#        restart: always
