version: '3.1'

services:

    mongodb-exporter:
        image: bitnami/mongodb-exporter
        ports:
            - 9216:9216
        command:
            - '--mongodb.uri=mongodb://root:123456@192.168.111.128:27017/admin?ssl=false'
            #- "--mongodb.uri=mongodb://user:pass@127.0.0.1:27017/admin?ssl=true"
        restart: always

