version: '3'

services:

  rabbitmq1:
    container_name: rabbitmq1
    image: rabbitmq:3.7.5-management
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - $PWD/data/rabbitmq1:/var/lib/rabbitmq/mnesia

  rabbitmq2:
    container_name: rabbitmq2
    image: rabbitmq:3.7.5-management
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - $PWD/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - $PWD/data/rabbitmq2:/var/lib/rabbitmq/mnesia
    entrypoint: sh /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    container_name: rabbitmq3
    image: rabbitmq:3.7.5-management
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - $PWD/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - $PWD/data/rabbitmq3:/var/lib/rabbitmq/mnesia
    entrypoint: sh /usr/local/bin/cluster-entrypoint.sh
    
  haproxy:
    container_name: haproxy
    image: haproxy:1.9
    restart: always
    volumes:
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
