version: '3'

services:
  mysql-master:
    image: mysql:8.0.18
    container_name: mysql-master
    restart: always
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/data/master:/var/lib/mysql
      - $PWD/config/master/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    networks:
      - mysql-master-slave-net

  mysql-slave1:
    image: mysql:8.0.18
    container_name: mysql-slave1
    restart: always
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/data/slave1:/var/lib/mysql
      - $PWD/config/slave1/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    networks:
      - mysql-master-slave-net


  mysql-slave2:
    image: mysql:8.0.18
    container_name: mysql-slave2
    restart: always
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - 33063:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/data/slave2:/var/lib/mysql
      - $PWD/config/slave2/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    networks:
      - mysql-master-slave-net

networks:
  mysql-master-slave-net:

