version: '3'

services:
  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
  
