version: '3'

services:
  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - $PWD/mysql-data:/var/lib/mysql
