version: '3.1'

volumes:
    prometheus1_data: {}
    prometheus2_data: {}
    prometheus3_data: {}
    prometheus4_data: {}
    minio_data: {}

services:
    prometheus-1:
        image: prom/prometheus:v2.25.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus1_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus1.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9081:9090
        #depends_on:
        #    - cadvisor
        restart: always
        networks:
          - thanos-net

    prometheus-2:
        image: prom/prometheus:v2.25.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus2_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus2.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9082:9090
        #depends_on:
        #    - cadvisor
        restart: always
        networks:
          - thanos-net

    prometheus-3:
        image: prom/prometheus:v2.25.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus3_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus3.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9083:9090
        #depends_on:
        #    - cadvisor
        restart: always
        networks:
          - thanos-net

    prometheus-4:
        image: prom/prometheus:v2.25.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus4_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus4.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9084:9090
        #depends_on:
        #    - cadvisor
        restart: always
        networks:
          - thanos-net

    thanos-sidecar-1:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus1_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-1:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-1
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-sidecar-2:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus2_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-2:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-2
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-sidecar-3:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus3_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-3:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-3
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-sidecar-4:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus4_data:/prometheus
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus-4:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - prometheus-4
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-querier:
        image: quay.io/thanos/thanos:v0.18.0
        command:
            - 'query'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--query.replica-label=replica'
            - '--store=thanos-sidecar-1:10091'
            - '--store=thanos-sidecar-2:10091'
            - '--store=thanos-sidecar-3:10091'
            - '--store=thanos-sidecar-4:10091'
            - '--store=thanos-store-gateway:10091'
        ports:
            - 10902:10902
        depends_on:
            - thanos-sidecar-1
            - thanos-sidecar-2
            - thanos-sidecar-3
            - thanos-sidecar-4
        restart: always
        networks:
          - thanos-net

    thanos-store-gateway:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'store'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--data-dir=/tmp/thanos/store'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
        depends_on:
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-compactor:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'compact'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - '--wait'
        depends_on:
            - minio
        restart: always
        networks:
          - thanos-net

    thanos-ruler:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'rule'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--eval-interval=15s'
            - '--rule-file=/etc/thanos/*.rules.yaml'
            - '--alertmanagers.url=http://alertmanager:9093'
            #- '--alertmanagers.url=http://192.168.6.169:8080'
            - '--query=thanos-querier:10902'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - "--label=ruler_cluster=\"vegas\""
            - "--label=ruler_replica=\"r1\""
        ports:
            - 10903:10902
        depends_on:
            - minio
            - thanos-querier
        restart: always
        networks:
          - thanos-net

    thanos-bucket-web:
        image: quay.io/thanos/thanos:v0.18.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - 'tools'
            - 'bucket'
            - 'web'
            - '--http-address=0.0.0.0:10902'
            - '--log.level=debug'
            - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
            - '--refresh=5m'
            - '--timeout=2m'
            - '--label=replica'
        ports:
            - 10904:10902
        depends_on:
            - minio
        restart: always
        networks:
          - thanos-net

    minio:
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        volumes:
            - minio_data:/data
        entrypoint: sh
        command: -c 'mkdir -p /data/demo-bucket && /usr/bin/minio server /data'
        environment:
            - MINIO_ACCESS_KEY=smth
            - MINIO_SECRET_KEY=Need8Chars
            - MINIO_PROMETHEUS_AUTH_TYPE=public
        ports:
            - 9000:9000
        networks:
          - thanos-net

    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports:
            - 9093:9093
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
            - '--config.file=/etc/alertmanager/config.yaml'
            - '--storage.path=/alertmanager'
        networks:
          - thanos-net

networks: 
  thanos-net:
    driver: bridge
