groups:
- name: linux_network_output__global__1627028570117953000
  rules:
  - alert: linux_network_output__P0
    expr: sum(irate(node_network_transmit_bytes_total{device!~"tap.*|veth.*|br.*|docker.*|virbr*|lo*"}[5m])*8/1024/1024)
      by (instance,project,company,enterprise,environment,server_usage) > 200
    for: 0m
    labels:
      level_id: "1"
      level_name: P0
      metric_full_name: linux_network_output
      metric_id: "16"
      scope: global
      version: "1627028570117953000"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 网络流出速度
  - alert: linux_network_output__P1
    expr: sum(irate(node_network_transmit_bytes_total{device!~"tap.*|veth.*|br.*|docker.*|virbr*|lo*"}[5m])*8/1024/1024)
      by (instance,project,company,enterprise,environment,server_usage) > 160
    for: 0m
    labels:
      level_id: "2"
      level_name: P1
      metric_full_name: linux_network_output
      metric_id: "16"
      scope: global
      version: "1627028570117953000"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 网络流出速度
  - alert: linux_network_output__P2
    expr: sum(irate(node_network_transmit_bytes_total{device!~"tap.*|veth.*|br.*|docker.*|virbr*|lo*"}[5m])*8/1024/1024)
      by (instance,project,company,enterprise,environment,server_usage) > 120
    for: 0m
    labels:
      level_id: "3"
      level_name: P2
      metric_full_name: linux_network_output
      metric_id: "16"
      scope: global
      version: "1627028570117953000"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 网络流出速度
  - alert: linux_network_output__P3
    expr: sum(irate(node_network_transmit_bytes_total{device!~"tap.*|veth.*|br.*|docker.*|virbr*|lo*"}[5m])*8/1024/1024)
      by (instance,project,company,enterprise,environment,server_usage) > 80
    for: 0m
    labels:
      level_id: "4"
      level_name: P3
      metric_full_name: linux_network_output
      metric_id: "16"
      scope: global
      version: "1627028570117953000"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 网络流出速度
  - alert: linux_network_output__P4
    expr: sum(irate(node_network_transmit_bytes_total{device!~"tap.*|veth.*|br.*|docker.*|virbr*|lo*"}[5m])*8/1024/1024)
      by (instance,project,company,enterprise,environment,server_usage) > 40
    for: 0m
    labels:
      level_id: "5"
      level_name: P4
      metric_full_name: linux_network_output
      metric_id: "16"
      scope: global
      version: "1627028570117953000"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 网络流出速度
