groups:
- name: linux_load1_usage__global__1626925020511977600
  rules:
  - alert: linux_load1_usage__P2
    expr: avg(node_load1{}) by (instance,project,company,enterprise,environment,server_usage)
      > 100
    for: 0m
    labels:
      level_id: "3"
      level_name: P2
      metric_full_name: linux_load1_usage
      metric_id: "7"
      scope: global
      version: "1626925020511977600"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 1分钟CPU平均负载
  - alert: linux_load1_usage__P3
    expr: avg(node_load1{}) by (instance,project,company,enterprise,environment,server_usage)
      > 50
    for: 0m
    labels:
      level_id: "4"
      level_name: P3
      metric_full_name: linux_load1_usage
      metric_id: "7"
      scope: global
      version: "1626925020511977600"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 1分钟CPU平均负载
  - alert: linux_load1_usage__P4
    expr: avg(node_load1{}) by (instance,project,company,enterprise,environment,server_usage)
      > 20
    for: 0m
    labels:
      level_id: "5"
      level_name: P4
      metric_full_name: linux_load1_usage
      metric_id: "7"
      scope: global
      version: "1626925020511977600"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 1分钟CPU平均负载
  - alert: linux_load1_usage__P0
    expr: avg(node_load1{}) by (instance,project,company,enterprise,environment,server_usage)
      > 200
    for: 0m
    labels:
      level_id: "1"
      level_name: P0
      metric_full_name: linux_load1_usage
      metric_id: "7"
      scope: global
      version: "1626925020511977600"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 1分钟CPU平均负载
  - alert: linux_load1_usage__P1
    expr: avg(node_load1{}) by (instance,project,company,enterprise,environment,server_usage)
      > 150
    for: 0m
    labels:
      level_id: "2"
      level_name: P1
      metric_full_name: linux_load1_usage
      metric_id: "7"
      scope: global
      version: "1626925020511977600"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 1分钟CPU平均负载
