groups:
- name: linux_cpu_usage__productName_147__1627039552191285500
  rules:
  - alert: linux_cpu_usage__P0
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle",project='D2SF产品研发项目2期'}[5m]))by
      (instance,project,company,enterprise,environment,server_usage) * 100 > 90
    for: 0m
    labels:
      level_id: "1"
      level_name: P0
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
  - alert: linux_cpu_usage__P1
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle",project='D2SF产品研发项目2期'}[5m]))by
      (instance,project,company,enterprise,environment,server_usage) * 100 > 85
    for: 0m
    labels:
      level_id: "2"
      level_name: P1
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
  - alert: linux_cpu_usage__P2
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle",project='D2SF产品研发项目2期'}[5m]))by
      (instance,project,company,enterprise,environment,server_usage) * 100 > 80
    for: 0m
    labels:
      level_id: "3"
      level_name: P2
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
  - alert: linux_cpu_usage__P3
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle",project='D2SF产品研发项目2期'}[5m]))by
      (instance,project,company,enterprise,environment,server_usage) * 100 > 75
    for: 0m
    labels:
      level_id: "4"
      level_name: P3
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
  - alert: linux_cpu_usage__P4
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle",project='D2SF产品研发项目2期'}[5m]))by
      (instance,project,company,enterprise,environment,server_usage) * 100 > 60
    for: 0m
    labels:
      level_id: "5"
      level_name: P4
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
  - alert: linux_cpu_usage__service_down
    expr: up == 0
    for: 0m
    labels:
      level_id: "1"
      level_name: P0
      metric_full_name: linux_cpu_usage
      metric_id: "6"
      product_id: "147"
      scope: productName_147
      version: "1627039552191285500"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: CPU使用率
