groups:
- name: linux_disk_usage__global__1627027897029644200
  rules:
  - alert: linux_disk_usage__P0
    expr: 100 - (sum((node_filesystem_avail_bytes{fstype=~"ext4|xfs"}) * 100) by (instance,project,company,enterprise,environment,server_usage)
      / sum(node_filesystem_size_bytes{fstype=~"ext4|xfs"})by (instance,project,company,enterprise,environment,server_usage))
      > 90
    for: 0m
    labels:
      level_id: "1"
      level_name: P0
      metric_full_name: linux_disk_usage
      metric_id: "9"
      scope: global
      unit: '%'
      version: "1627027897029644200"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 磁盘使用率
  - alert: linux_disk_usage__P1
    expr: 100 - (sum((node_filesystem_avail_bytes{fstype=~"ext4|xfs"}) * 100) by (instance,project,company,enterprise,environment,server_usage)
      / sum(node_filesystem_size_bytes{fstype=~"ext4|xfs"})by (instance,project,company,enterprise,environment,server_usage))
      > 75
    for: 0m
    labels:
      level_id: "2"
      level_name: P1
      metric_full_name: linux_disk_usage
      metric_id: "9"
      scope: global
      unit: '%'
      version: "1627027897029644200"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 磁盘使用率
  - alert: linux_disk_usage__P2
    expr: 100 - (sum((node_filesystem_avail_bytes{fstype=~"ext4|xfs"}) * 100) by (instance,project,company,enterprise,environment,server_usage)
      / sum(node_filesystem_size_bytes{fstype=~"ext4|xfs"})by (instance,project,company,enterprise,environment,server_usage))
      > 70
    for: 0m
    labels:
      level_id: "3"
      level_name: P2
      metric_full_name: linux_disk_usage
      metric_id: "9"
      scope: global
      unit: '%'
      version: "1627027897029644200"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 磁盘使用率
  - alert: linux_disk_usage__P3
    expr: 100 - (sum((node_filesystem_avail_bytes{fstype=~"ext4|xfs"}) * 100) by (instance,project,company,enterprise,environment,server_usage)
      / sum(node_filesystem_size_bytes{fstype=~"ext4|xfs"})by (instance,project,company,enterprise,environment,server_usage))
      > 65
    for: 0m
    labels:
      level_id: "4"
      level_name: P3
      metric_full_name: linux_disk_usage
      metric_id: "9"
      scope: global
      unit: '%'
      version: "1627027897029644200"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 磁盘使用率
  - alert: linux_disk_usage__P4
    expr: 100 - (sum((node_filesystem_avail_bytes{fstype=~"ext4|xfs"}) * 100) by (instance,project,company,enterprise,environment,server_usage)
      / sum(node_filesystem_size_bytes{fstype=~"ext4|xfs"})by (instance,project,company,enterprise,environment,server_usage))
      > 60
    for: 0m
    labels:
      level_id: "5"
      level_name: P4
      metric_full_name: linux_disk_usage
      metric_id: "9"
      scope: global
      unit: '%'
      version: "1627027897029644200"
    annotations:
      summary: '{{ $labels.instance }}'
      value: '{{ $value }}'
      description: 磁盘使用率
